### ISSUE TITLE
Fixa Quiz när ingen emoji är fångad

### ISSUE THREAD

**Issue by dasovm** [ericwenn/TeamTurtle#49]
### Fixa Quiz

Just nu när man klarar en bana utan att fångat några emojis, så kraschar spelet.
Ska vi bara slumpa fram något ord och svarsalternativ ifall de inte fångat något?

**Comment by RasmusJemth** [comment]
Antingen slumpa ord eller ta något ord som var med på banan blir nog bra

**Comment by dasovm** [comment]
Ifall ingen emoji fångas kommer spelaren inte till quiz:et, utan hamnar direkt i vinst-skärmen.
