### ISSUE TITLE
Prestationer "skrivs över"

### ISSUE THREAD

**Issue by RasmusJemth** [ericwenn/TeamTurtle#57]
Om man klarar en bana och får 3 stjärnor, sen kör om banan och bara får 1 stjärna, då kommer det stå att man har 1 stjärna på den banan på level screen

**Comment by ericwenn** [comment]
Fixar så att den bara skriver över om man får fler stjärnor än man hade tidigare.

**Comment by ericwenn** [comment]
Fixat.
