### ISSUE TITLE
Fixa mountains.png

### ISSUE THREAD

**Issue by RasmusJemth** [ericwenn/TeamTurtle#74]
Det ser konstigt ut där bakgrunden med bergen möts, kan någon fixa det. 
![backgrundsglitch](https://cloud.githubusercontent.com/assets/16309894/19272880/a3a2160c-8fca-11e6-99e4-5d66f39c9ed1.png)
![background](https://cloud.githubusercontent.com/assets/16309894/19272886/abedb73a-8fca-11e6-97d4-01a68651294b.png)

**Comment by danahlq** [comment]
Fixar detta nu

**Comment by danahlq** [comment]
Fixat
